FROM python:3.11.0rc2-alpine3.16

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./
# ADD ./src/config.yaml ./
RUN ls

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0" ]
