# builder image
FROM golang:alpine3.16 as builder
RUN mkdir /build
ADD ./src/*.go /build/
ADD ./go.* /build/
WORKDIR /build
RUN CGO_ENABLED=0 GOOS=linux go build -a -o service .

FROM golang:alpine3.16
RUN mkdir /app
WORKDIR /app
ADD ./src/config.yaml ./
COPY --from=builder /build/service /app
ENTRYPOINT [ "/app/service" ]
